org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# IMPORTANT for Kotlin/Compose stability
kotlin.daemon.jvm.options=-Xmx2g

API_NINJAS_KEY=8S1JnN6xGZjaFD3tDphLPppFEobb9ptHG9D4zHgR